# Generated by Django 5.0.4 on 2024-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_student_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='school',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='schools', to='apis.classroom'),
        ),
    ]
